### ISSUE TITLE
Characteristic.CurrentHeatingCoolingState returns invalid value 3

### ISSUE THREAD

**Issue by didole66** [davidborzek/homebridge-dummy-thermostat#3]
According to the Homebridge spec (https://developers.homebridge.io/#/characteristic/CurrentHeatingCoolingState), "CurrentHeatingCoolingState" should only return values 0, 1, 2 - if the thermostat is set to "auto" mode, it should return the mode it is actually running in ("off", "heating" or "cooling"), not the "auto" mode it was set to.

I therefore get tons of warnings in Homebridge when I set the mode to "auto":

[3/6/2021, 16:21:51] [TestThermostat] 3
[3/6/2021, 16:21:51] [homebridge-dummy-thermostat] This plugin generated a warning from the characteristic 'Current Heating Cooling State': characteristic was supplied illegal value: number 3 exceeded maximum of 2. See https://git.io/JtMGR for more info.

**Comment by fuzzydunlop1976** [comment]
I also get this error in homebridge logs. It is also switching the thermostat off within HomeKit when set to auto mode. I really wanted to use the auto mode as a condition in automations so hoping it might be fixed as the plugin works really well other than this.

**Comment by davidborzek** [comment]
Fixed in [48c41b1](https://github.com/davidborzek/homebridge-dummy-thermostat/commit/48c41b1ad9a21b7e7881c5b640a7aea3f606f235)
